### ISSUE TITLE
"A summary has not been generated for this dataset yet."

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#45]
When might we see this message?

Looking at staging 2 of the feeds have this message but the rest have summaries. I'm wondering if there's a failure condition, e.g feed is unreachable?

If so, then perhaps we can store an error code and display that?

**Comment by digitalWestie** [comment]
This message appears when summary `samples == 0`. This would be the case if summary gathering was restarted (or started for the first time), and the endpoint wasn't reachable for whatever reason. 

If a summary was gathered at any point in time (so samples>0), it will continue to show those results. To test things out I've manually been running the summary script with the restart option so I've killed previous summaries that were scheduled. 

If a summary had been gathered a week ago, and it hadn't worked since, it would still show a summary. Aside from looking at the `last_updated` to see how old it was, it would probably look like it was working.   

So perhaps besides a `last_updated` timestamp, a `last_attempt` error code & timestamp could be useful?

**Comment by digitalWestie** [comment]
OK - this already proved useful! I thought the Fusion dataset was falling over but something else is up. I think the modified timestamp is a bit off?

https://fusion-lifestyle-openactive.azurewebsites.net/api/sessions
